name: Bug Report
description: "Report something that's broken in Jetstream Rise."
body:
  - type: markdown
    attributes:
      value: "For minor issues like documentation typos or IDE warnings, please submit a pull request instead of creating an issue."
  - type: input
    attributes:
      label: Jetstream Rise Version
      description: Provide the Jetstream Rise version that you are using.
      placeholder: 1.0.0
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Framework Stack
      options:
        - React
        - Svelte
        - Inertia
        - Livewire
    validations:
      required: true
  - type: input
    attributes:
      label: Laravel Version
      description: Provide the Laravel version that you are using. [Ensure it is still supported.](https://laravel.com/docs/releases#support-policy)
      placeholder: 10.4.1
    validations:
      required: true
  - type: input
    attributes:
      label: PHP Version
      description: Provide the PHP version that you are using.
      placeholder: 8.1.4
    validations:
      required: true
  - type: input
    attributes:
      label: Database Driver & Version
      description: If applicable, provide the database driver and version you are using.
      placeholder: "MySQL 8.0.31 for macOS 13.0 on arm64 (Homebrew)"
    validations:
      required: false
  - type: textarea
    attributes:
      label: Description
      description: Provide a detailed description of the issue you are experiencing.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Provide detailed steps to reproduce your issue. Include code samples or a GitHub repository (`laravel new bug-report --github="--public"`) if necessary.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: Describe the behavior you expected to see.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Actual Behavior
      description: Describe the actual behavior you observed.
    validations:
      required: false
